### ISSUE TITLE
 Cannot load <class 'model.unet_2d_condition.UNet2DConditionModel'> from /home/jay/StoryGen/ckpt/stable-diffusion-v1-5/ because the following keys are missing

### ISSUE THREAD

**Issue by Yu1stra** [haoningwu3639/StoryGen#22]
Thank you for your contribution in visual storytelling research, these problem occurs when I execute "CUDA_VISIBLE_DEVICES=0 accelerate launch inference.py", and I also download pre-trained StableDiffusion-1.5 from SDM. Do I need to training the model first or I forgot some steps before I execute the command? Please help me to fix this problem, thank you very much.
My anaconda env settting is some as the Requirements, and I running on RTX4080 by linux system.

Traceback (most recent call last):
  File "inference.py", line 146, in <module>
    test(pretrained_model_path,
  File "inference.py", line 52, in test
    unet = UNet2DConditionModel.from_pretrained(pretrained_model_path, subfolder="unet")
  File "/home/jay/.conda/envs/storygen/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 565, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'model.unet_2d_condition.UNet2DConditionModel'> from /home/jay/StoryGen/ckpt/stable-diffusion-v1-5/ because the following keys are missing:
 up_blocks.1.attentions.1.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.1.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.2.attentions.0.transformer_blocks.0.attn3.to_k.weight, down_blocks.1.attentions.1.transformer_blocks.0.attn3.to_q.weight, up_blocks.2.attentions.1.transformer_blocks.0.attn3.to_out.0.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn3.to_q.weight, down_blocks.2.attentions.0.transformer_blocks.0.norm4.weight, down_blocks.0.attentions.0.transformer_blocks.0.norm4.bias, up_blocks.2.attentions.0.transformer_blocks.0.norm4.bias, up_blocks.1.attentions.1.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.3.attentions.1.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.1.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, down_blocks.1.attentions.1.transformer_blocks.0.norm4.bias, down_blocks.1.attentions.1.transformer_blocks.0.norm4.weight, up_blocks.1.attentions.2.transformer_blocks.0.attn3.to_v.weight, up_blocks.3.attentions.1.transformer_blocks.0.attn3.to_q.weight, up_blocks.2.attentions.2.transformer_blocks.0.attn3.to_out.0.weight, mid_block.attentions.0.transformer_blocks.0.norm4.weight, down_blocks.1.attentions.1.transformer_blocks.0.attn3.to_v.weight, up_blocks.3.attentions.2.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.0.attentions.1.transformer_blocks.0.norm4.weight, mid_block.attentions.0.transformer_blocks.0.attn3.to_q.weight, down_blocks.2.attentions.1.transformer_blocks.0.attn3.to_v.weight, up_blocks.1.attentions.2.transformer_blocks.0.attn3.to_k.weight, up_blocks.3.attentions.1.transformer_blocks.0.attn3.to_v.weight, up_blocks.3.attentions.2.transformer_blocks.0.attn3.to_q.weight, up_blocks.2.attentions.1.transformer_blocks.0.norm4.weight, up_blocks.3.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.3.attentions.1.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.3.attentions.1.transformer_blocks.0.norm4.bias, up_blocks.3.attentions.0.transformer_blocks.0.attn3.to_k.weight, up_blocks.1.attentions.1.transformer_blocks.0.attn3.to_v.weight, up_blocks.1.attentions.1.transformer_blocks.0.attn3.to_k.weight, up_blocks.3.attentions.0.transformer_blocks.0.attn3.to_v.weight, up_blocks.2.attentions.0.transformer_blocks.0.attn3.to_q.weight, down_blocks.2.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.3.attentions.0.transformer_blocks.0.attn3.to_q.weight, up_blocks.2.attentions.1.transformer_blocks.0.attn3.to_q.weight, up_blocks.1.attentions.2.transformer_blocks.0.norm4.bias, down_blocks.0.attentions.1.transformer_blocks.0.attn3.to_q.weight, up_blocks.2.attentions.2.transformer_blocks.0.attn3.to_v.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.1.attentions.1.transformer_blocks.0.norm4.weight, down_blocks.2.attentions.1.transformer_blocks.0.norm4.weight, up_blocks.1.attentions.0.transformer_blocks.0.attn3.to_v.weight, up_blocks.2.attentions.2.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.1.attentions.0.transformer_blocks.0.attn3.to_k.weight, down_blocks.2.attentions.1.transformer_blocks.0.attn3.to_q.weight, up_blocks.3.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.1.attentions.0.transformer_blocks.0.norm4.weight, down_blocks.1.attentions.0.transformer_blocks.0.attn3.to_v.weight, up_blocks.2.attentions.2.transformer_blocks.0.norm4.weight, mid_block.attentions.0.transformer_blocks.0.norm4.bias, down_blocks.2.attentions.1.transformer_blocks.0.attn3.to_k.weight, down_blocks.1.attentions.1.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.2.attentions.0.transformer_blocks.0.attn3.to_k.weight, up_blocks.2.attentions.1.transformer_blocks.0.norm4.bias, up_blocks.1.attentions.2.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.1.attentions.0.transformer_blocks.0.norm4.bias, down_blocks.0.attentions.1.transformer_blocks.0.attn3.to_v.weight, up_blocks.3.attentions.2.transformer_blocks.0.norm4.weight, up_blocks.3.attentions.1.transformer_blocks.0.attn3.to_k.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.3.attentions.2.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.2.attentions.0.transformer_blocks.0.norm4.weight, down_blocks.1.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, mid_block.attentions.0.transformer_blocks.0.attn3.to_v.weight, up_blocks.2.attentions.1.transformer_blocks.0.attn3.to_k.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn3.to_v.weight, up_blocks.1.attentions.2.transformer_blocks.0.attn3.to_out.0.weight, up_blocks.2.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.1.attentions.0.transformer_blocks.0.attn3.to_q.weight, mid_block.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.1.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.3.attentions.1.transformer_blocks.0.norm4.weight, down_blocks.2.attentions.0.transformer_blocks.0.attn3.to_q.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn3.to_k.weight, up_blocks.1.attentions.2.transformer_blocks.0.norm4.weight, up_blocks.3.attentions.2.transformer_blocks.0.attn3.to_v.weight, up_blocks.3.attentions.2.transformer_blocks.0.attn3.to_k.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.2.attentions.1.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.2.attentions.2.transformer_blocks.0.attn3.to_k.weight, down_blocks.1.attentions.0.transformer_blocks.0.norm4.bias, up_blocks.3.attentions.0.transformer_blocks.0.norm4.bias, up_blocks.2.attentions.1.transformer_blocks.0.attn3.to_v.weight, up_blocks.1.attentions.1.transformer_blocks.0.attn3.to_q.weight, mid_block.attentions.0.transformer_blocks.0.attn3.to_k.weight, up_blocks.2.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, mid_block.attentions.0.transformer_blocks.0.attn3.to_out.0.weight, down_blocks.0.attentions.0.transformer_blocks.0.norm4.weight, up_blocks.2.attentions.2.transformer_blocks.0.attn3.to_q.weight, down_blocks.2.attentions.1.transformer_blocks.0.norm4.bias, down_blocks.0.attentions.1.transformer_blocks.0.norm4.bias, up_blocks.2.attentions.1.transformer_blocks.0.attn3.to_out.0.bias, up_blocks.1.attentions.0.transformer_blocks.0.attn3.to_k.weight, up_blocks.1.attentions.1.transformer_blocks.0.norm4.bias, up_blocks.3.attentions.2.transformer_blocks.0.norm4.bias, down_blocks.0.attentions.0.transformer_blocks.0.attn3.to_k.weight, up_blocks.2.attentions.2.transformer_blocks.0.norm4.bias, down_blocks.1.attentions.0.transformer_blocks.0.norm4.weight, up_blocks.2.attentions.0.transformer_blocks.0.attn3.to_v.weight, up_blocks.1.attentions.2.transformer_blocks.0.attn3.to_q.weight, up_blocks.1.attentions.0.transformer_blocks.0.attn3.to_q.weight, up_blocks.3.attentions.0.transformer_blocks.0.norm4.weight, down_blocks.2.attentions.0.transformer_blocks.0.norm4.bias, down_blocks.1.attentions.1.transformer_blocks.0.attn3.to_out.0.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.2.attentions.0.transformer_blocks.0.attn3.to_out.0.bias, down_blocks.2.attentions.1.transformer_blocks.0.attn3.to_out.0.weight, down_blocks.2.attentions.0.transformer_blocks.0.attn3.to_v.weight, down_blocks.1.attentions.1.transformer_blocks.0.attn3.to_k.weight.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomely initialize those weights or else make sure your checkpoint file is correct.
Traceback (most recent call last):
  File "/home/jay/.conda/envs/storygen/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jay/.conda/envs/storygen/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/jay/.conda/envs/storygen/lib/python3.8/site-packages/accelerate/commands/launch.py", line 915, in launch_command
    simple_launcher(args)
  File "/home/jay/.conda/envs/storygen/lib/python3.8/site-packages/accelerate/commands/launch.py", line 578, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jay/.conda/envs/storygen/bin/python', 'inference.py']' returned non-zero exit status 1.

**Comment by haoningwu3639** [comment]
If you want to train our StoryGen based on pre-trained Stable Diffusion, as described in our README, please refer to https://github.com/haoningwu3639/StoryGen/issues/12#issuecomment-2002917015 for the initialization of the model.
And if you want to directly inference with our pre-trained StoryGen checkpoints, please download our ckpts from https://huggingface.co/haoningwu/StoryGen and load them as described in our README.

**Comment by Yu1stra** [comment]
Thank you for response!!
